version: 0.0
os: linux
files:
  - source: ./Dockerfile
    destination: /webservice
  - source: ./target
    destination: /webservice
  - source: ./build_expose.sh
    destination: /webservice
#  - source: Config/config.txt
#    destination: /webapps/Config
#  - source: source
#    destination: /webapps/myApp
hooks:
#  BeforeInstall:
#    - location: Scripts/UnzipResourceBundle.sh
#    - location: Scripts/UnzipDataBundle.sh
#  AfterInstall:
#    - location: Scripts/RunResourceTests.sh
#      timeout: 180
  ApplicationStart:
    - location: build_expose.sh
      timeout: 3600
      runas: root
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser